spring.aplication.name: heroku_c45a332bde5369e
server.port: ${PORT:0}

spring.datasource.url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_c45a332bde5369euser=b3f0e4b24c05e6&password=07083a6b
spring.datasource.username: b3f0e4b24c05e6
spring.datasource.password: 07083a6b
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
spring.thymeleaf.cache: false

server:
    port:8080